spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - cn.dev33.satoken.dao.SaTokenDaoRedisJackson
  datasource:
    url: jdbc:h2:mem:cmc;MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=USER,FUNCTION,LOG;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:db/schema-demo.sql

server:
  port: 8080

app:
  upload:
    dir: upload

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  token-style: tik
  is-read-header: true
  is-read-cookie: false
  timeout: 86400

knife4j:
  enable: true
