server:
  port: 8080

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  upload:
    dir: upload

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  token-style: tik
  is-read-header: true
  is-read-cookie: false
  timeout: 86400

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.cmc: debug
    com.cmc.mapper: debug
